### ISSUE TITLE
Is there an Issue with Ubuntu 20.04

### ISSUE THREAD

**Issue by 0xMDIV** [BeepIsla/CSGO-Overwatch-Bot#122]
On my Raspberry Pi with Raspbian Buster everything works
but on Ubuntu 20.04 i cant even start the Script always get an Error Message:

static OverwatchConstants = {
                                  ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/projects/csgo/overwatchbot/index.js:8:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

You have an Idea why this happens?

**Comment by BeepIsla** [comment]
Update NodeJS according to the README.

> NodeJS 12+ version
