### ISSUE TITLE
Parsing: 0%TypeError: Cannot read property 'xuid' of null

### ISSUE THREAD

**Issue by estiawan** [BeepIsla/CSGO-Overwatch-Bot#138]
hello, i have problem with force.js in my demo it says "Parsing: 0%TypeError: Cannot read property 'xuid' of null"

> Download : [here](https://s3.froidgaming.net/demo/auto-20200919-142422-de_dust2.dem.bz2)
> Steam Suspect : 76561198838001362
> 
> The Suspect start playing on round 1 - end

**Comment by BeepIsla** [comment]
What is the full error? Just the title doesn't help a lot.

**Comment by estiawan** [comment]
```
TypeError: Cannot read property 'xuid' of null
    at Player.get steam64Id [as steam64Id] (C:\CSGO-Overwatch-Bot-master\node_modules\demofile\dist\entities\player.js:91:26)
    at C:\CSGO-Overwatch-Bot-master\helpers\Demo.js:332:54
    at Array.find (<anonymous>)
    at Demo.findSuspect (C:\CSGO-Overwatch-Bot-master\helpers\Demo.js:332:42)
    at Demo.getSuspectInfo (C:\CSGO-Overwatch-Bot-master\helpers\Demo.js:294:8)
    at GameEvents.emit (events.js:327:22)
    at C:\CSGO-Overwatch-Bot-master\node_modules\demofile\dist\gameevents.js:30:22
    at Array.forEach (<anonymous>)
    at DemoFile.<anonymous> (C:\CSGO-Overwatch-Bot-master\node_modules\demofile\dist\gameevents.js:29:30)
    at DemoFile.emit (events.js:327:22)
    at DemoFile._parseRecurse (C:\CSGO-Overwatch-Bot-master\node_modules\demofile\dist\demo.js:233:14)
    at processImmediate (internal/timers.js:456:21)

TypeError: Cannot read property 'xuid' of null
    at Player.get steam64Id [as steam64Id] (C:\CSGO-Overwatch-Bot-master\node_modules\demofile\dist\entities\player.js:91:26)
    at C:\CSGO-Overwatch-Bot-master\helpers\Demo.js:332:54
    at Array.find (<anonymous>)
    at Demo.findSuspect (C:\CSGO-Overwatch-Bot-master\helpers\Demo.js:332:42)
    at Demo.getSuspectInfo (C:\CSGO-Overwatch-Bot-master\helpers\Demo.js:294:8)
    at GameEvents.emit (events.js:327:22)
    at C:\CSGO-Overwatch-Bot-master\node_modules\demofile\dist\gameevents.js:30:22
    at Array.forEach (<anonymous>)
    at DemoFile.<anonymous> (C:\CSGO-Overwatch-Bot-master\node_modules\demofile\dist\gameevents.js:29:30)
    at DemoFile.emit (events.js:327:22)
    at DemoFile._parseRecurse (C:\CSGO-Overwatch-Bot-master\node_modules\demofile\dist\demo.js:233:14)
    at processImmediate (internal/timers.js:456:21)
```

**Comment by estiawan** [comment]
Thanks @BeepIsla
