### ISSUE TITLE
RateLimitExceeded

### ISSUE THREAD

**Issue by xSuspect** [BeepIsla/CSGO-Overwatch-Bot#152]
"version": "2.5.0",
/home/csgo/index.js:344
                        throw err;
                        ^

Error: RateLimitExceeded
    at SteamUser.<anonymous> (/home/csgo/node_modules/steam-user/components/logon.js:494:16)
    at /home/csgo/node_modules/steam-user/components/classes/HandlerManager.js:37:12
    at Array.forEach (<anonymous>)
    at HandlerManager.emit (/home/csgo/node_modules/steam-user/components/classes/HandlerManager.js:36:12)
    at SteamUser._handleMessage (/home/csgo/node_modules/steam-user/components/messages.js:571:24)
    at SteamUser.Coordinator.steamUser._handleMessage (/home/csgo/helpers/Coordinator.js:22:19)
    at SteamUser._handleNetMessage (/home/csgo/node_modules/steam-user/components/messages.js:506:7)
    at SteamUser.processMulti (/home/csgo/node_modules/steam-user/components/messages.js:598:9)
    at SteamUser.<anonymous> (/home/csgo/node_modules/steam-user/components/messages.js:592:16)
    at /home/csgo/node_modules/steam-user/components/classes/HandlerManager.js:37:12
    at Array.forEach (<anonymous>)
    at HandlerManager.emit (/home/csgo/node_modules/steam-user/components/classes/HandlerManager.js:36:12)
    at SteamUser._handleMessage (/home/csgo/node_modules/steam-user/components/messages.js:571:24)
    at SteamUser.Coordinator.steamUser._handleMessage (/home/csgo/helpers/Coordinator.js:22:19)
    at SteamUser._handleNetMessage (/home/csgo/node_modules/steam-user/components/messages.js:506:7)
    at TCPConnection._readMessage (/home/csgo/node_modules/steam-user/components/connection_protocols/tcp.js:193:12) {
  eresult: 84
}

**Comment by BeepIsla** [comment]
Too many logins too fast, wait 30 minutes. Do not try to login again, if you do the timer resets.
