### ISSUE TITLE
RangeError: Array buffer allocation failed

### ISSUE THREAD

**Issue by yasinshot46** [BeepIsla/CSGO-Overwatch-Bot#183]
----- The whole demo will be analyzed ----
Downloading demo...
Unpacking demo...
Received a 117.10MB demo
-  Server: Valve CS:GO pwrd_uc_tianjin Server (srcds075.228.22)
- Version: 13770
-     Map: de_inferno
-  Length: 49:10m
Parsing: 0%
RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at new Uint8Array (<anonymous>)
    at new FastBuffer (internal/buffer.js:940:1)
    at Function.alloc (buffer.js:338:10)
    at new Buffer (buffer.js:251:19)
    at Function.module.exports.ByteBuffer.wrap (/data/data/com.termux/files/home/bot/node_modules/bytebuffer/dist/bytebuffer-node.js:357:17)
    at DemoFile.parse (/data/data/com.termux/files/home/bot/node_modules/demofile/dist/demo.js:145:36)
    at /data/data/com.termux/files/home/bot/helpers/Demo.js:291:14
    at new Promise (<anonymous>)
    at Demo.parse (/data/data/com.termux/files/home/bot/helpers/Demo.js:177:10)
    at Coordinator.<anonymous> (/data/data/com.termux/files/home/bot/index.js:610:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Disconnected from Steam with EResult 3 and message NoConnection

**Comment by BeepIsla** [comment]
#30
