### ISSUE TITLE
events.js:292

### ISSUE THREAD

**Issue by ESLCarlos1610** [BeepIsla/CSGO-Overwatch-Bot#185]
Hey, i tryed to setup my Overwatchbot to an account. At other accounts the bot worked but here not. Idk what is the problem, so please help me xD

events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: RateLimitExceeded
    at SteamUser.<anonymous> (C:\Users\nicko\OneDrive\Desktop\cs\CSGO-Overwatch-Bot-master\node_modules\steam-user\components\logon.js:494:16)
    at C:\Users\nicko\OneDrive\Desktop\cs\CSGO-Overwatch-Bot-master\node_modules\steam-user\components\classes\HandlerManager.js:37:12
    at Array.forEach (<anonymous>)
    at HandlerManager.emit (C:\Users\nicko\OneDrive\Desktop\cs\CSGO-Overwatch-Bot-master\node_modules\steam-user\components\classes\HandlerManager.js:36:12)
    at SteamUser._handleMessage (C:\Users\nicko\OneDrive\Desktop\cs\CSGO-Overwatch-Bot-master\node_modules\steam-user\components\messages.js:571:24)
    at SteamUser._handleNetMessage (C:\Users\nicko\OneDrive\Desktop\cs\CSGO-Overwatch-Bot-master\node_modules\steam-user\components\messages.js:506:7)
    at SteamUser.processMulti (C:\Users\nicko\OneDrive\Desktop\cs\CSGO-Overwatch-Bot-master\node_modules\steam-user\components\messages.js:598:9)
    at SteamUser.<anonymous> (C:\Users\nicko\OneDrive\Desktop\cs\CSGO-Overwatch-Bot-master\node_modules\steam-user\components\messages.js:592:16)
    at C:\Users\nicko\OneDrive\Desktop\cs\CSGO-Overwatch-Bot-master\node_modules\steam-user\components\classes\HandlerManager.js:37:12
    at Array.forEach (<anonymous>)
Emitted 'error' event on process instance at:
    at emitUnhandledRejectionOrErr (internal/event_target.js:545:11)
    at MessagePort.[nodejs.internal.kHybridDispatch] (internal/event_target.js:358:9)
    at MessagePort.exports.emitMessage (internal/per_context/messageport.js:18:26) {
  eresult: 84

**Comment by BeepIsla** [comment]
Read the error, you failed to successfully login to an account too many times and have been ratelimited. Wait 30 minutes without touching anything and try again, if you try again too soon the 30 minutes reset.
