### ISSUE TITLE
events.js:292       throw er; // Unhandled 'error'

### ISSUE THREAD

**Issue by Kofro** [BeepIsla/CSGO-Overwatch-Bot#199]
Removed the full directory for security.

\CSGO-Overwatch-Bot-master>node index.js
Checking protobufs...
Found protobufs
Checking for updates...
Up to date!
Fetching CSGO translation file...
Logging into Steam...
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: RateLimitExceeded
    at SteamUser.<anonymous> (\CSGO-Overwatch-Bot-master\node_modules\steam-user\components\logon.js:494:16)
    at \node_modules\steam-user\components\classes\HandlerManager.js:37:12
    at Array.forEach (<anonymous>)
    at HandlerManager.emit (\CSGO-Overwatch-Bot-master\node_modules\steam-user\components\classes\HandlerManager.js:36:12)
    at SteamUser._handleMessage (\CSGO-Overwatch-Bot-master\node_modules\steam-user\components\messages.js:571:24)
    at SteamUser._handleNetMessage (\CSGO-Overwatch-Bot-master\node_modules\steam-user\components\messages.js:506:7)
    at SteamUser.processMulti (\CSGO-Overwatch-Bot-master\node_modules\steam-user\components\messages.js:598:9)
    at SteamUser.<anonymous> (\CSGO-Overwatch-Bot-master\node_modules\steam-user\components\messages.js:592:16)
    at\CSGO-Overwatch-Bot-master\node_modules\steam-user\components\classes\HandlerManager.js:37:12
    at Array.forEach (<anonymous>)
Emitted 'error' event on process instance at:
    at emitUnhandledRejectionOrErr (internal/event_target.js:545:11)
    at MessagePort.[nodejs.internal.kHybridDispatch] (internal/event_target.js:358:9)
    at MessagePort.exports.emitMessage (internal/per_context/messageport.js:18:26) {
  eresult: 84
}

Removed the full directory for security.

**Comment by BeepIsla** [comment]
#185
