### ISSUE TITLE
Force.js cannot read property 'fractionid' of undefined 

### ISSUE THREAD

**Issue by Steve6030** [BeepIsla/CSGO-Overwatch-Bot#205]
While trying to use force.js to analyze local demo file in the CSGO-Overwatch-Bot-master directory, getting error below.

Syntax used: node .\force.js 003486959825215029423_0874806338_191 76561198898391543
Demo File name: 003486959825215029423_0874806338_191.dem

```
PS C:\Users\Steve\Downloads\CSGO-Overwatch-Bot-master> node .\force.js 003486959825215029423_0874806338_191 76561198898391543
? Write logs to file (Leave empty to not write):
Parsing demo with suspect 76561198898391543
Parsing: 0%TypeError: Cannot read property 'fractionid' of undefined
    at DemoFile.<anonymous> (C:\Users\Steve\Downloads\CSGO-Overwatch-Bot-master\helpers\Demo.js:226:57)
    at DemoFile.emit (events.js:327:22)
    at DemoFile._parseRecurse (C:\Users\Steve\Downloads\CSGO-Overwatch-Bot-master\node_modules\demofile\dist\demo.js:219:22)
    at processImmediate (internal/timers.js:461:21)

TypeError: Cannot read property 'fractionid' of undefined
    at DemoFile.<anonymous> (C:\Users\Steve\Downloads\CSGO-Overwatch-Bot-master\helpers\Demo.js:226:57)
    at DemoFile.emit (events.js:327:22)
    at DemoFile._parseRecurse (C:\Users\Steve\Downloads\CSGO-Overwatch-Bot-master\node_modules\demofile\dist\demo.js:219:22)
    at processImmediate (internal/timers.js:461:21)
```

**Comment by BeepIsla** [comment]
I see where the problem is in the code, I will fix it later today.

**Comment by BeepIsla** [comment]
Should now be fixed
