### ISSUE TITLE
Run error in linux

### ISSUE THREAD

**Issue by TheZafkiel** [BeepIsla/CSGO-Overwatch-Bot#216]
I try to run it in linux and there seems to be some problems
![lin](https://user-images.githubusercontent.com/61747242/132089227-6470bfb8-3cb9-4c9b-9a83-b74ed6eff231.jpg)
----
/www/wwwroot/CSGO-Overwatch-Bot/index.js:45
(async () => {
       ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)

**Comment by BeepIsla** [comment]
Seems like you are running some *very* ancient NodeJS version. As per README the minimum version is 12. Search up how to update NodeJS on your distro and try again.

**Comment by TheZafkiel** [comment]
Thanks, I can use it after updating nodejs
