### ISSUE TITLE
Error when downloading china demos?

### ISSUE THREAD

**Issue by zacharykkkk** [BeepIsla/CSGO-Overwatch-Bot#30]
Please read [this comment below](https://github.com/BeepIsla/CSGO-Overwatch-Bot/issues/30#issuecomment-618524735) instead.

Original issue:

---

```
Requested Overwatch case
Downloading case 3409316132287414618 from url http://replay228.wmsj.cn/730/003409313158022562053_0745470960.dem.bz2
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo EAI_AGAIN replay228.wmsj.cn
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
Emitted 'error' event on Request instance at:
    at Request.onRequestError (C:\overwatch\node_modules\request\request.js:881:8)
    at ClientRequest.emit (events.js:315:20)
    at Socket.socketErrorListener (_http_client.js:432:9)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:84:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: -3001,
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'replay228.wmsj.cn'
}
```

Tried using a US VPN, still randomly downloads China demos. Any idea what's up?

And it gets stuck at downloading case for a long time, before generating the error.

**Comment by BeepIsla** [comment]
Just because you are in the US or anywhere doesn't mean you can't get demos to review from China.

I was able to download this demo just fine.

EAI_AGAIN is a DNS lookup timed out error, means it is a network connectivity error or proxy related error.

**Comment by zacharykkkk** [comment]
Sorry I think I copied the wrong code. This is the actual one.

`Downloading case 3409408527771369573 from url http://replay233.wmsj.cn/730/003409406294388375584_0068853565.dem.bz2
Finished downloading 3409408527771369573, unpacking...
internal/streams/legacy.js:61
      throw er; // Unhandled stream error in pipe.
      ^

TypeError: Cannot read property '0' of undefined
    at f (C:\overwatch\node_modules\unbzip2-stream\lib\bit_iterator.js:30:34)
    at Object.bzip2.decompress (C:\overwatch\node_modules\unbzip2-stream\lib\bzip2.js:283:28)
    at decompressBlock (C:\overwatch\node_modules\unbzip2-stream\index.js:30:29)
    at decompressAndQueue (C:\overwatch\node_modules\unbzip2-stream\index.js:47:20)
    at Stream.end (C:\overwatch\node_modules\unbzip2-stream\index.js:82:17)
    at _end (C:\overwatch\node_modules\through\index.js:65:9)
    at Stream.stream.end (C:\overwatch\node_modules\through\index.js:74:5)
    at ReadStream.onend (_stream_readable.js:673:10)
    at Object.onceWrapper (events.js:421:28)
    at ReadStream.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1201:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)`

**Comment by BeepIsla** [comment]
If this is still an issue: Can you try downloading the demo manually? Just click the link and see if you can play it in CSGO's demo viewer.

**Comment by zacharykkkk** [comment]
it does work but not on the cmd prompt

**Comment by Borlax2** [comment]
same issue since morning, couldn't download a single demo, all failed:

TypeError: Cannot read property '0' of undefined

**Comment by BeepIsla** [comment]
Released version 2.0 - This might be fixed or not, re-open if not fixed.

**Comment by Borlax2** [comment]
Running `10` BOTS accounts, `7 to 8` of them taking too long to download the demo, and once the demo downloaded, I get the below error:
`TypeError: Cannot read property '0' of undefined`

(New OverWatch BOT Version 2.0)
One of the Demo links: http://replay233.wmsj.cn/730/003433116856766955622_1950165108.dem.bz2

**Comment by BeepIsla** [comment]
Perfect World downloads are extremely slow, they seem to be limiting downloads to ~200 KB/s.

**Comment by Borlax2** [comment]
Don't ask me, Ask China :D

**Comment by Borlax2** [comment]
I think valve fixed this in their latest update, seems to be working fine now.  Anyone still having this issue?

**Comment by MackyReborn** [comment]
Is this due to the fact that perfect world demos are of a higher tickrate and the buffer isn't big enough to hold the data?

**Comment by BeepIsla** [comment]
I never heard if PW demos being higher tickrate, I doubt it. Even if they are bigger JS buffers are dynamic, if more size is needed it just makes more

**Comment by DJMarkus1337** [comment]
@BeepIsla you have discord ?

**Comment by DJMarkus1337** [comment]
I wanted to ask something on private

**Comment by BeepIsla** [comment]
I do not give out my Discord. Whatever you want I am not interested.
