### ISSUE TITLE
getting error while running

### ISSUE THREAD

**Issue by 1nhale** [BeepIsla/CSGO-Overwatch-Bot#34]
getting the below error while trying to run. Please tell me what the issue is :(
`node index.js
Steam Guard App Code: *****
internal/fs/utils.js:656
    throw new ERR_INVALID_ARG_TYPE(
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (142)
    at Object.writeFile (fs.js:1356:5)
    at FileStorage.saveFile.FileStorage.writeFile (/data/data/com.termux/files/home/storage/CSGO-Overwatch-Bot/node_modules/file-manager/index.js:68:5)
    at SteamUser.<anonymous> (/data/data/com.termux/files/home/storage/CSGO-Overwatch-Bot/node_modules/steam-user/components/logon.js:371:18)
    at /data/data/com.termux/files/home/storage/CSGO-Overwatch-Bot/node_modules/steam-user/components/classes/HandlerManager.js:37:12
    at Array.forEach (<anonymous>)
    at HandlerManager.emit (/data/data/com.termux/files/home/storage/CSGO-Overwatch-Bot/node_modules/steam-user/components/classes/HandlerManager.js:36:12)
    at SteamUser._handleMessage (/data/data/com.termux/files/home/storage/CSGO-Overwatch-Bot/node_modules/steam-user/components/messages.js:548:24)
    at SteamUser._handleNetMessage (/data/data/com.termux/files/home/storage/CSGO-Overwatch-Bot/node_modules/steam-user/components/messages.js:474:7)
    at SteamUser.processMulti (/data/data/com.termux/files/home/storage/CSGO-Overwatch-Bot/node_modules/steam-user/components/messages.js:575:9)
    at Gunzip.cb (/data/data/com.termux/files/home/storage/CSGO-Overwatch-Bot/node_modules/steam-user/components/messages.js:566:17)
    at Gunzip.zlibBufferOnEnd (zlib.js:151:10)
    at Gunzip.emit (events.js:315:20)
    at endReadableNT (_stream_readable.js:1218:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'ERR_INVALID_ARG_TYPE'`

**Comment by BeepIsla** [comment]
Config?

**Comment by 1nhale** [comment]
`{
	"account": {
		"username": "*****",
		"password": "*****",
		"sharedSecret": ""
	},
	"parsing": {
		"steamWebAPIKey": "*****",
		"minimumTime": 240,
		"aimbot": {
			"maxTicks": 10,
			"threshold": 1.0
		},
		"afking": {
			"radius": 80
		}
	},
	"verdict": {
		"writeLog": false,
		"backupDemo": false,
		"maxVerdicts": 0,
		"maxAimbot": 3,
		"maxWallKills": 2,
		"maxTeamKills": 1,
		"maxTeamDamage": 180,
		"maxAFKing": 3
	},
	"richPresence": {
		 "steam_display": "#bcast_teamvsteammap",
         "team1": "OPPONENT",
         "team2": "MYSELF",
         "map": "de_mirage"
	}
}
`

**Comment by BeepIsla** [comment]
I don't really know where the error could come from, I assume it is related to you trying to run it on Termux. Does the same happen when you try to run it on your normal machine?

**Comment by 1nhale** [comment]
nope.. it runs smoothly on the pc.. I just wanted to run it on my android phone (cannot keep my pc on 24/7), i suppose this is some error related to write accessibility, Maybe some limitation or termux/android

**Comment by BeepIsla** [comment]
Make sure your Termux has READ/WRITE permissions for files, I am not experienced with Termux so I can't really help, sorry.
