### ISSUE TITLE
Error after entering steam guard code

### ISSUE THREAD

**Issue by lavascience** [BeepIsla/CSGO-Overwatch-Bot#36]
After entering my steam guard code having run node index.js, i get this message
internal/fs/utils.js:658
    throw new ERR_INVALID_ARG_TYPE(
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (4)
    at Object.writeFile (fs.js:1356:5)
    at FileStorage.saveFile.FileStorage.writeFile (D:\CSGO-Overwatch-Bot-master\node_modules\file-manager\index.js:68:5)    at SteamUser.<anonymous> (D:\CSGO-Overwatch-Bot-master\node_modules\steam-user\components\logon.js:371:18)
    at D:\CSGO-Overwatch-Bot-master\node_modules\steam-user\components\classes\HandlerManager.js:37:12
    at Array.forEach (<anonymous>)
    at HandlerManager.emit (D:\CSGO-Overwatch-Bot-master\node_modules\steam-user\components\classes\HandlerManager.js:36:12)
    at SteamUser._handleMessage (D:\CSGO-Overwatch-Bot-master\node_modules\steam-user\components\messages.js:548:24)
    at SteamUser._handleNetMessage (D:\CSGO-Overwatch-Bot-master\node_modules\steam-user\components\messages.js:474:7)
    at SteamUser.processMulti (D:\CSGO-Overwatch-Bot-master\node_modules\steam-user\components\messages.js:575:9)
    at Gunzip.cb (D:\CSGO-Overwatch-Bot-master\node_modules\steam-user\components\messages.js:566:17)
    at Gunzip.zlibBufferOnEnd (zlib.js:151:10)
    at Gunzip.emit (events.js:315:20)
    at endReadableNT (_stream_readable.js:1225:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'ERR_INVALID_ARG_TYPE'
}****

I'm not sure how to solve it, as it seems that its something to do with the code itself.

**Comment by BeepIsla** [comment]
This doesn't look like its related to the bot it self but an underlying library.

Can you try the following:

1. Run `npm install steam-user`

2. Try again

3. Tell me if the error continues or if it works now

**Comment by lavascience** [comment]
Works just fine now, thank you!

**Comment by BeepIsla** [comment]
It seems like the old `steam-user` version was the issue here, I have updated it to automatically install the latest version (0faa22145e13f5ad3be15cdbf15c77958597959a)
