### ISSUE TITLE
Issues on Linux Server

### ISSUE THREAD

**Issue by OscarLam1337** [BeepIsla/CSGO-Overwatch-Bot#45]
Tried to use it on a linux server but faced an issue, it crashes sometimes without a reason.

`
Requested Overwatch case
Downloading case 3416345831962312954 from url http://replay142.valve.net/730/003416334828256100362_0503133639.dem.bz2
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo EAI_AGAIN replay142.valve.net replay142.valve.net:80
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
Emitted 'error' event at:
    at Request.onRequestError (/home/keta/owbot/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:198:13)
    at Socket.socketErrorListener (_http_client.js:401:9)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
`

**Comment by BeepIsla** [comment]
> EAI_AGAIN is a DNS lookup timed out error, means it is a network connectivity error or proxy related error.

Likely related to your server having network problems.
