### ISSUE TITLE
RangeError: Array buffer allocation failed

### ISSUE THREAD

**Issue by aevdokimovshs** [BeepIsla/CSGO-Overwatch-Bot#46]
This happens to me after a few resolved cases when the next case is downloading

 ` Downloading case 3417223482759446585 from url http://replay234.wmsj.cn/730/003417166458478657690_0562809877.dem.bz2
Finished downloading 3417223482759446585, unpacking...
Finished unpacking 3417223482759446585, parsing as suspect 76561199046853717...
`

Error:
`RangeError: Array buffer allocation failed
at new ArrayBuffer (<anonymous>)
at new Uint8Array (<anonymous>)
at new FastBuffer (buffer.js:79:1)
at Function.alloc (buffer.js:282:10)
at new Buffer (buffer.js:179:19)
at Function.module.exports.ByteBuffer.wrap (/root/CSGO-Overwatch-Bot/node_modules/bytebuffer/dist/bytebuffer-node.js:357:17)
at DemoFile.parse (/root/CSGO-Overwatch-Bot/node_modules/demofile/dist/demo.js:131:36)
at fs.readFile (/root/CSGO-Overwatch-Bot/index.js:278:16)
at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
`

**Comment by BeepIsla** [comment]
I cannot replicate this

**Comment by aevdokimovshs** [comment]
Yes, it works, but I want to add that the tool will try to download the demo again and after an indefinite number of attempts it will download it

**Comment by BeepIsla** [comment]
That seems very odd, I don't know how this could possibly happen. Maybe perfect world limiting downloads in some way.

**Comment by aevdokimovshs** [comment]
This error appears on Debian 10. I will try to install another OS. On Windows everything is fine.

**Comment by aevdokimovshs** [comment]
I installed Debian 8 and now everything is fine, thanks. Maybe there was a problem in NodeJS
