### ISSUE TITLE
How can I solve this error?

### ISSUE THREAD

**Issue by destinius** [BeepIsla/CSGO-Overwatch-Bot#53]
--------------------
Requested Overwatch case
Downloading case 3420438635147690139 from url http://replay233.wmsj.cn/730/003420
internal/streams/legacy.js:61
      throw er; // Unhandled stream error in pipe.
      ^

TypeError: Cannot read property '0' of undefined
    at f (C:\Users\Administrator\Downloads\CSGO-Overwatch-Bot-master\node_modules
    at Object.bzip2.decompress (C:\Users\Administrator\Downloads\CSGO-Overwatch-B
    at decompressBlock (C:\Users\Administrator\Downloads\CSGO-Overwatch-Bot-maste
    at decompressAndQueue (C:\Users\Administrator\Downloads\CSGO-Overwatch-Bot-ma
    at Stream.end (C:\Users\Administrator\Downloads\CSGO-Overwatch-Bot-master\nod
    at _end (C:\Users\Administrator\Downloads\CSGO-Overwatch-Bot-master\node_modu
    at Stream.stream.end (C:\Users\Administrator\Downloads\CSGO-Overwatch-Bot-mas
    at ReadStream.onend (_stream_readable.js:682:10)
    at Object.onceWrapper (events.js:421:28)
    at ReadStream.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by BeepIsla** [comment]
Related to #30

---

I don't know what the problem is, I don't know how to fix it. It seems to only happen with Perfect World demos.
