### ISSUE TITLE
 Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by ramboi234** [BeepIsla/CSGO-Overwatch-Bot#56]
first-4 case this happend sometimes, 
full error log : 

$ node index
Successfully logged into 76561198426952999
Checking protobufs...
Found protobufs
Checking for updates...
Establishing CSGO GameCoordinator connection...
We are Master Guardian II with 384 wins
We are likely able to request Overwatch cases. Trying to start case handler...
--------------------
Requested Overwatch case
Downloading case 3422348647906410656 from url http://replay228.wmsj.cn/730/00342
2341904807755886_0127573991.dem.bz2
Finished downloading 3422348647906410656, unpacking...
internal/streams/legacy.js:61
      throw er; // Unhandled stream error in pipe.
      ^

TypeError: Cannot read property '0' of undefined
    at f (C:\Users\ranboi\Desktop\CSGO-Overwatch-Bot-master\node_modules\unbzip2-
stream\lib\bit_iterator.js:30:34)
    at Object.bzip2.decompress (C:\ranboi\annis\Desktop\CSGO-Overwatch-Bot-master
\node_modules\unbzip2-stream\lib\bzip2.js:283:28)
    at decompressBlock (C:\Users\ranboi\Desktop\CSGO-Overwatch-Bot-master\node_mo
dules\unbzip2-stream\index.js:30:29)
    at decompressAndQueue (C:\Users\ranboi\Desktop\CSGO-Overwatch-Bot-master\node
_modules\unbzip2-stream\index.js:47:20)
    at Stream.end (C:\Users\ranboi\Desktop\CSGO-Overwatch-Bot-master\node_modules
\unbzip2-stream\index.js:82:17)
    at _end (C:\Users\ranboi\Desktop\CSGO-Overwatch-Bot-master\node_modules\throu
gh\index.js:65:9)
    at Stream.stream.end (C:\Users\ranboi\Desktop\CSGO-Overwatch-Bot-master\node_
modules\through\index.js:74:5)
    at ReadStream.onend (_stream_readable.js:679:10)
    at Object.onceWrapper (events.js:417:28)
    at ReadStream.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by BeepIsla** [comment]
Duplicate #30 

In short: Unknown issue with demos from China, likely Perfect World. Solution: None. Just wait a few hours until the case is solved and you can get a new one.
