### ISSUE TITLE
Cant login while username and password is correct

### ISSUE THREAD

**Issue by luanium1811** [BeepIsla/CSGO-Overwatch-Bot#57]
PS C:\Users\eZuw\Desktop\CSGO-Overwatch-Bot-master> node index.js
Error: InvalidPassword
    at SteamUser.<anonymous> (C:\Users\eZuw\Desktop\CSGO-Overwatch-Bot-master\node_modules\steam-user\components\logon.js:494:16)
    at C:\Users\eZuw\Desktop\CSGO-Overwatch-Bot-master\node_modules\steam-user\components\classes\HandlerManager.js:37:12
    at Array.forEach (<anonymous>)
    at HandlerManager.emit (C:\Users\eZuw\Desktop\CSGO-Overwatch-Bot-master\node_modules\steam-user\components\classes\HandlerManager.js:36:12)
    at SteamUser._handleMessage (C:\Users\eZuw\Desktop\CSGO-Overwatch-Bot-master\node_modules\steam-user\components\messages.js:569:24)
    at SteamUser._handleNetMessage (C:\Users\eZuw\Desktop\CSGO-Overwatch-Bot-master\node_modules\steam-user\components\messages.js:504:7)
    at SteamUser.processMulti (C:\Users\eZuw\Desktop\CSGO-Overwatch-Bot-master\node_modules\steam-user\components\messages.js:596:9)
    at SteamUser.<anonymous> (C:\Users\eZuw\Desktop\CSGO-Overwatch-Bot-master\node_modules\steam-user\components\messages.js:590:16)
    at C:\Users\eZuw\Desktop\CSGO-Overwatch-Bot-master\node_modules\steam-user\components\classes\HandlerManager.js:37:12
    at Array.forEach (<anonymous>)
    at HandlerManager.emit (C:\Users\eZuw\Desktop\CSGO-Overwatch-Bot-master\node_modules\steam-user\components\classes\HandlerManager.js:36:12)
    at SteamUser._handleMessage (C:\Users\eZuw\Desktop\CSGO-Overwatch-Bot-master\node_modules\steam-user\components\messages.js:569:24)
    at SteamUser._handleNetMessage (C:\Users\eZuw\Desktop\CSGO-Overwatch-Bot-master\node_modules\steam-user\components\messages.js:504:7)
    at TCPConnection._readMessage (C:\Users\eZuw\Desktop\CSGO-Overwatch-Bot-master\node_modules\steam-user\components\connection_protocols\tcp.js:193:12)
    at Socket.emit (events.js:315:20)
    at emitReadable_ (_stream_readable.js:556:12) {
  eresult: 5
}
PS C:\Users\eZuw\Desktop\CSGO-Overwatch-Bot-master>

**Comment by BeepIsla** [comment]
Well, Steam rejects them. Whats your config? Censor sensitive data before posting.

**Comment by luanium1811** [comment]
i use ur default config, only change username, password and steam api key

**Comment by BeepIsla** [comment]
Works just fine for me, make sure there are no invisible characters or any spaces in your password/username. If you do not use a `sharedSecret` make sure it is an empty string (`""`)

**Comment by luanium1811** [comment]
yes. its work fine for another account but just 1 account i cant use. my password and username only normal word, no special characters.

**Comment by BeepIsla** [comment]
That does not make sense, I don't know why this happens. I sadly cannot help you with this.
