### ISSUE TITLE
node index.js

### ISSUE THREAD

**Issue by vyeeechor** [BeepIsla/CSGO-Overwatch-Bot#62]
PS C:\Users\Kamil\Desktop\CSGO-Overwatch-Bot-master> node index.js
internal/modules/cjs/loader.js:1175
    throw err;
    ^

SyntaxError: C:\Users\Kamil\Desktop\CSGO-Overwatch-Bot-master\config.json: Unexpected token G in JSON at position 111
    at parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1172:22)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\Kamil\Desktop\CSGO-Overwatch-Bot-master\index.js:17:16)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47

**Comment by BeepIsla** [comment]
Config?

**Comment by vyeeechor** [comment]
{
	"account": {
		"username": "ExampleUsername",
		"password": "ExamplePassword",
		"sharedSecret": ""
	},
	"parsing": {
		"steamWebAPIKey": "ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",
		"minimumTime": 240,
		"aimbot": {
			"maxTicks": 10,
			"threshold": 1.0
		},
		"afking": {
			"radius": 80
		}
	},
	"verdict": {
		"writeLog": true,
		"backupDemo": false,
		"maxVerdicts": 0,
		"maxAimbot": 10,
		"maxWallKills": 7,
		"maxTeamKills": 1,
		"maxTeamDamage": 180,
		"maxAFKing": 3
	},
	"richPresence": {
		"steam_display": "#display_overwatch"
	}
}

**Comment by BeepIsla** [comment]
1. You need to read the README and actually fill out the config.

2. That error says there is a problem at character 111 which is a unexpected `G`, but there is none.

**Comment by vyeeechor** [comment]
working fine! 

i remove special character to the password :P 

Sorry for my english
