### ISSUE TITLE
Cannot find module 'steam-user'

### ISSUE THREAD

**Issue by ruwenj** [BeepIsla/CSGO-Overwatch-Bot#94]
Since the update the bot can't finde module 'steam-user'

`internal/modules/cjs/loader.js:895
    throw err;
    ^
Error: Cannot find module 'steam-user'
Require stack:
- /root/overwatch/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:892:15)
    at Function.Module._load (internal/modules/cjs/loader.js:785:27)
    at Module.require (internal/modules/cjs/loader.js:956:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/root/overwatch/index.js:4:19)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
    at Module.load (internal/modules/cjs/loader.js:914:32)
    at Function.Module._load (internal/modules/cjs/loader.js:822:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1143:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/root/overwatch/index.js' ]
}`

**Comment by BeepIsla** [comment]
Run `npm ci`
